services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: studymate-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root123456
      MYSQL_DATABASE: studymate_dev
      MYSQL_USER: studymate
      MYSQL_PASSWORD: 12345
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - studymate-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "studymate", "-p12345"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Content Service (Backend)
  content-service:
    build: 
      context: ./backend/content-service
      dockerfile: Dockerfile
    container_name: studymate-content-service
    restart: unless-stopped
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: studymate
      DB_PASSWORD: 12345
      DB_NAME: studymate_dev
      PORT: 3003
      NODE_ENV: development
      JWT_SECRET: your-super-secret-jwt-key-here-change-in-production
      AUTH_SERVICE_URL: http://auth-service:3005
      USER_PROFILE_SERVICE_URL: http://user-profile-service:3006
    ports:
      - "3003:3003"
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./backend/content-service/uploads:/app/uploads
    networks:
      - studymate-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3003/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # User Service (Backend)
  user-service:
    build: 
      context: ./backend/user-service
      dockerfile: Dockerfile
    container_name: studymate-user-service
    restart: unless-stopped
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: studymate
      DB_PASSWORD: 12345
      DB_NAME: studymate_dev
      PORT: 3005
      NODE_ENV: development
      JWT_SECRET: your-super-secret-jwt-key-here-change-in-production
      JWT_EXPIRES_IN: 24h
      JWT_REFRESH_EXPIRES_IN: 7d
    ports:
      - "3005:3005"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - studymate-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3005/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # API Gateway (Backend)
  api-gateway:
    build: 
      context: ./gateway
      dockerfile: Dockerfile
    container_name: studymate-api-gateway
    restart: unless-stopped
    environment:
      PORT: 3000
      NODE_ENV: development
    ports:
      - "3000:3000"
    depends_on:
      content-service:
        condition: service_healthy
      user-service:
        condition: service_healthy
    networks:
      - studymate-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend (React)
  frontend:
    build:
      context: ./frontend/studymate-frontend
      dockerfile: Dockerfile
    container_name: studymate-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - content-service
    networks:
      - studymate-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis (for caching and sessions)
  redis:
    image: redis:7-alpine
    container_name: studymate-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - studymate-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # phpMyAdmin (for database management)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: studymate-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: studymate
      PMA_PASSWORD: 12345
    ports:
      - "8080:80"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - studymate-network

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local

networks:
  studymate-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
